- name: Installer les dépendances pour Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Ajouter la clé GPG officielle de Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    validate_certs: false

- name: Ajouter le repository Docker
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
    state: present
    validate_certs: false


- name: Installer Docker Engine et le plugin Compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: S'assurer que le service Docker est démarré
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Créer le dossier Uptime Kuma
  ansible.builtin.file:
    path: /opt/Uptime_Kuma
    state: directory
    mode: '0755'

- name: Vérifier présence du docker compose dans /opt 
  ansible.builtin.stat:
    path: /opt/Uptime_Kuma/docker-compose.yml
  register: docker_compose_check

- name: Copier le docker-compose
  ansible.builtin.template:
    src: /Infra_GSB/Ansible/roles/Uptime_Kuma/templates/docker-compose.yml
    dest: /opt/Uptime_Kuma/docker-compose.yml
    remote_src: no
  when: not docker_compose_check.stat.exists 

- name: Lancer le docker-compose
  community.docker.docker_compose_v2:
    project_src: /opt/Uptime_Kuma
    state: present

- name: Restaurer la conf du Uptime Kuma
  ansible.builtin.copy:
    src: data/
    dest: /var/lib/docker/volumes/uptime_kuma_kuma_db/_data/
    mode: "0755" 
  notify: Redémarrer Uptime_Kuma
