name: Build & Deploy Flutter Web (via WireGuard VPN)

on:
  push:
    branches:
      - main
    paths:
      - 'site/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard

      - name: Configure VPN
        run: |
          echo "${{ secrets.WG_CONF }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          sleep 5
          echo "VPN interface:"
          ip addr show wg0
          echo "VPN peers:"
          sudo wg

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'

      - name: Build Flutter Web
        run: |
          cd site
          flutter pub get
          flutter build web --release

      - name: Deploy to internal server (via VPN)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "site/build/web/*"
          target: "/var/www/html/m2shelper/"
